#!/bin/bash
# Quick demo of Local 2FA Authenticator

echo "═══════════════════════════════════════════════════════════"
echo "      LOCAL 2FA AUTHENTICATOR - QUICK DEMO"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "This is a fully local, encrypted 2FA authenticator."
echo "All data is stored encrypted on your machine."
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "COMMON USAGE:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "# Add a new account (auto-generates secret + shows QR code)"
echo "  ./local_2fa.py add github"
echo ""
echo "# Add account with existing secret from service"
echo "  ./local_2fa.py add aws --secret JBSWY3DPEHPK3PXP"
echo ""
echo "# Get a 6-digit code"
echo "  ./local_2fa.py get github"
echo ""
echo "# Watch mode (auto-refresh all codes in real-time)"
echo "  ./local_2fa.py watch"
echo ""
echo "# List all accounts"
echo "  ./local_2fa.py list"
echo ""
echo "# Show QR code for mobile app"
echo "  ./local_2fa.py qr github"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "LOCATION:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "  Script: /home/mrc/experiment/cappuccino/local_2fa.py"
echo "  Guide:  /home/mrc/experiment/cappuccino/2FA_GUIDE.txt"
echo "  Vault:  ~/.local_2fa_vault.enc (created on first use)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "SECURITY:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "  ✓ AES-256 encryption"
echo "  ✓ PBKDF2 key derivation (100,000 iterations)"
echo "  ✓ Local storage only (no cloud, no network)"
echo "  ✓ File permissions: 600 (owner only)"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Read the full guide: cat 2FA_GUIDE.txt"
echo ""
