#!/bin/bash
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          CAPPUCCINO - ORGANIZED DIRECTORY STRUCTURE            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📁 cappuccino/"
echo "├── 📂 scripts/ ..................... Executable scripts (55 files)"
echo "│   ├── training/ .................. Training & optimization (10)"
echo "│   ├── data/ ...................... Data download/prep (8)"
echo "│   ├── deployment/ ................ Model deployment (7)"
echo "│   ├── automation/ ................ System control (20)"
echo "│   └── optimization/ .............. Analysis/validation (10)"
echo "│"
echo "├── 📂 logs/ ........................ Log files (2,632 files)"
echo "│   ├── training/ .................. Training logs ⭐"
echo "│   ├── data/ ...................... Data processing logs"
echo "│   ├── system/ .................... System logs"
echo "│   └── archive/ ................... Old logs"
echo "│"
echo "├── 📂 docs/ ........................ Documentation (55 files)"
echo "│   ├── guides/ .................... User guides ⭐"
echo "│   ├── reports/ ................... Analysis reports"
echo "│   └── status/ .................... Status updates"
echo "│"
echo "├── 📂 processors/ .................. Data processors (5 files)"
echo "│   ├── processor_Alpaca.py ........ Alpaca (14 indicators) ⭐"
echo "│   ├── processor_CGE.py ........... Synthetic data"
echo "│   ├── processor_FRED.py .......... Economic data"
echo "│   └── preprocessor.py ............ Preprocessing utils"
echo "│"
echo "├── 📂 monitoring/ .................. Monitoring tools (12 files)"
echo "│   ├── check_status.sh ............ Quick status ⭐"
echo "│   ├── monitor_training.sh ........ Training monitor ⭐"
echo "│   └── dashboard.py ............... Main dashboard"
echo "│"
echo "├── 📂 models/ ...................... Model definitions (8 files)"
echo "│   ├── ensemble_agent.py"
echo "│   ├── adaptive_ensemble_agent.py"
echo "│   └── model_arena.py"
echo "│"
echo "├── 📂 databases/ ................... Optuna databases (29 files)"
echo "│   └── optuna_cappuccino.db ....... Main study DB"
echo "│"
echo "├── 📂 utils/ ....................... Utility functions (17 files)"
echo "│   ├── function_CPCV.py ........... Cross-validation"
echo "│   ├── fee_tier_manager.py ........ Fee management"
echo "│   └── alert_system.py ............ Alerts"
echo "│"
echo "├── 📂 infrastructure/ .............. Deployment configs"
echo "│   ├── docker/ .................... Docker files"
echo "│   └── integration/ ............... Integrations"
echo "│"
echo "├── 📂 data/ ........................ Training data"
echo "│   └── 1h_1680/ ................... Current dataset (14 ind) ⭐"
echo "│"
echo "├── 📂 drl_agents/ .................. RL agent core"
echo "├── 📂 config/ ...................... Additional configs"
echo "├── 📂 tests/ ....................... Test files"
echo "├── 📂 archive/ ..................... Old/deprecated files"
echo "│"
echo "└── 📄 Root Files (core modules)"
echo "    ├── config_main.py .............. Main configuration ⭐"
echo "    ├── constants.py ................ System constants"
echo "    ├── environment_Alpaca.py ....... Trading environment"
echo "    └── DIRECTORY_STRUCTURE.md ...... This structure guide ⭐"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  Total: 2,813 organized files across 30+ logical folders"
echo "════════════════════════════════════════════════════════════════"
